name: Gospel Studio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffefe'
    - '#000000'
    - '#363636'
    - '#636363'
    - '#c7c7c7'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
